### ISSUE TITLE
Possible stale docstring & new maximum enquiry

### ISSUE THREAD

**Issue by IHarperCircle** [carter-j-h/iterable-python-wrapper#8]
[This docstring](https://github.com/carter-j-h/iterable-python-wrapper/blob/10d5db034ddfdfc3333efeee07fc9228b6a998c4/iterablepythonwrapper/client.py#L1385) says that only 50 users can be bulk uploaded at a time, but I have been able to upload in batches of 1600 users. If this is expected, what is the new maximum number of users that can be uploaded to Iterable using the `bulk_update_user()` method?

**Comment by julianmclain** [comment]
Hi @IHarperCircle - I believe the actual limit is based on request size vs. number of users. If you want to keep it on the safe side, I've found that batches of 1,000 users works well.
